swagger: "2.0"
info:
  description: A simple helloworld service
  version: "1.0.0"
  title: OpenAPI REST 
#host: "tfcndemo.endpoints.simple-terraform-demo-001.cloud.goog"
#x-google-endpoints:
#- name: "tfcndemo.endpoints.simple-terraform-demo-001.cloud.goog"
#  target: "35.246.116.87"
host: ${service_name}
x-google-endpoints:
    - name: ${service_name}
      target: ${ip_address}

consumes:
  - "application/json"
produces:
  - "application/json"
#schemes: [http, https]

basePath: "/api"

paths:
  /helloworld:
    get:
      tags: [Helloworld]
      operationId: helloworld.read
      summary: "Returns helloworld"
      description: "Get helloworld"
      responses:
        '200':
          description: "Successful"

  /health:
    get:
      tags: [Health]
      operationId: health.health
      summary: Health Check
      responses:
        '200':
          description: Status message for current health


